mysql:
  host: 127.0.0.1
  port: 3306
  config: ""
  db: gvb_db
  user: root
  password: root1234
  log_level: dev
logger:
  level: info
  prefix: '[gvb_server]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  post: 8080
  env: release
site_info:
  created_at: "2023-09-12"
  bei_an: ""
  title: GVB
  qq_image: ""
  version: v3
  email: 1227891082@qq.com
  wechat_image: ""
  name: LXJ
  job: 全栈开发
  addr: 深圳
  slogan: LXJ
  slogan_en: LXJ
  web: ""
