mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: root1234
  log_level: release
logger:
  level: info
  prefix: '[gvb_server]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  post: 8080
  env: release
site_info:
  created_at: "2023-09-12"
  bei_an: xxxx
  title: GVB
  qq_image: xxxx
  version: v4
  email: 1227891082@qq.com
  wechat_image: xxxx
  name: LXJ
  job: 全栈开发
  addr: 深圳
  slogan: LXJ
  slogan_en: LXJ
  web: xxxx
qi_niu:
  enable: true
  access_key: jbOdFNbXoiC6zEhKUtT-rSqtKbt1Ytu1vIUBTSqc
  secret_key: d55oZTrdnEsk_qEGOj0WQv7GZcquNlWuDsvdELSK
  bucket: 202100203017
  cdn: http://s0yvn46ks.hn-bkt.clouddn.com/
  zone: z2
  size: 20
  prefix: gvb
email:
  host: ""
  port: 0
  user: 1227891082@qq.com
  password: password
  default_from_email: LXJ
  user_ssl: true
  user_tls: true
jwt:
  secret: 0x0372ACFEB262
  expires: 2
  issuer: LXJ
qq:
  app_id: xxx
  key: xxx
  redirect: xxx
static:
  size: 20
  path: static/file